---
checks:
  check_template: github.com/scorify/check-template@v1.0.3
  ping: github.com/scorify/ping@v1.0.1
  http: github.com/scorify/http@v0.0.5
  ssh: github.com/scorify/ssh@v0.0.1
  dns: github.com/scorify/dns@v0.0.3
  ftp: github.com/scorify/ftp@v0.0.2
  ldap: github.com/scorify/ldap@v0.0.3
  mysql: github.com/scorify/mysql@v0.0.2
  smb: github.com/scorify/smb@v0.0.3
  winrm: github.com/scorify/winrm@v0.0.2
  tcp: github.com/scorify/tcp@v0.0.1
  smtp: github.com/scorify/smtp@v0.0.0
  imap: github.com/scorify/imap@v0.0.0