FROM node:20.12-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json vite.config.ts tsconfig.json tsconfig.node.json index.html /app/
COPY src /app/src
COPY public /app/public

RUN npm install && npm run build

FROM caddy:2.8.4-alpine

WORKDIR /app
COPY --from=builder /app/dist /app/
COPY Caddyfile /etc/caddy/Caddyfile