// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/scorify/scorify/pkg/ent/injectsubmission"
	"github.com/scorify/scorify/pkg/ent/predicate"
)

// InjectSubmissionDelete is the builder for deleting a InjectSubmission entity.
type InjectSubmissionDelete struct {
	config
	hooks    []Hook
	mutation *InjectSubmissionMutation
}

// Where appends a list predicates to the InjectSubmissionDelete builder.
func (isd *InjectSubmissionDelete) Where(ps ...predicate.InjectSubmission) *InjectSubmissionDelete {
	isd.mutation.Where(ps...)
	return isd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (isd *InjectSubmissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, isd.sqlExec, isd.mutation, isd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (isd *InjectSubmissionDelete) ExecX(ctx context.Context) int {
	n, err := isd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (isd *InjectSubmissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(injectsubmission.Table, sqlgraph.NewFieldSpec(injectsubmission.FieldID, field.TypeUUID))
	if ps := isd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, isd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	isd.mutation.done = true
	return affected, err
}

// InjectSubmissionDeleteOne is the builder for deleting a single InjectSubmission entity.
type InjectSubmissionDeleteOne struct {
	isd *InjectSubmissionDelete
}

// Where appends a list predicates to the InjectSubmissionDelete builder.
func (isdo *InjectSubmissionDeleteOne) Where(ps ...predicate.InjectSubmission) *InjectSubmissionDeleteOne {
	isdo.isd.mutation.Where(ps...)
	return isdo
}

// Exec executes the deletion query.
func (isdo *InjectSubmissionDeleteOne) Exec(ctx context.Context) error {
	n, err := isdo.isd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{injectsubmission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (isdo *InjectSubmissionDeleteOne) ExecX(ctx context.Context) {
	if err := isdo.Exec(ctx); err != nil {
		panic(err)
	}
}
