// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/scorify/ftp@v0.0.0"

package checks

import (
	ftp "github.com/scorify/ftp"
)

func init() {
	Checks["ftp"] = Check{
		Func:   ftp.Run,
		Schema: ConvertSchema(ftp.Schema{}),
	}
}