// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/scorify/imap@v0.0.0"

package checks

import (
	"github.com/scorify/schema"

	imap "github.com/scorify/imap"
)

func init() {
	schema, err := schema.Describe(imap.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["imap"] = Check{
		Func:     imap.Run,
		Validate: imap.Validate,
		Schema:   schema,
	}
}