// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/scorify/ldap@v0.0.0"

package checks

import (
	ldap "github.com/scorify/ldap"
)

func init() {
	Checks["ldap"] = Check{
		Func:   ldap.Run,
		Schema: ConvertSchema(ldap.Schema{}),
	}
}