// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/scorify/ping@v1.0.2"

package checks

import (
	"github.com/scorify/schema"

	ping "github.com/scorify/ping"
)

func init() {
	schema, err := schema.Describe(ping.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["ping"] = Check{
		Func:     ping.Run,
		Validate: ping.Validate,
		Schema:   schema,
	}
}